build_script:
  - ps: "Invoke-WebRequest https://github.com/ysangkok/pgp-win32-6.5.8/archive/master.zip -OutFile master.zip"
  - ps: "Expand-Archive master.zip"
  - ps: "Move-Item pgp-win32-6.5.8-master\\libs ."
  - ps: "(new-object net.webclient).DownloadFile('https://ci.appveyor.com/api/buildjobs/ygqch73yb4pq1d1e/artifacts/libs/pgpcdk/win32/PGPcdk/Release/PGPsdkStatic.lib', 'libs\\pgpcdk\\win32\\PGPcdk\\Release\\PGPsdkStatic.lib')"
  - cmd: "msbuild src\\win32\\PGPfone.sln /logger:\"C:\\Program Files\\AppVeyor\\BuildAgent\\Appveyor.MSBuildLogger.dll\""
