#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: "Invoke-WebRequest https://github.com/ysangkok/pgp-win32-6.5.8/archive/master.zip -OutFile master.zip"
  - ps: "Expand-Archive -LiteralPath master.zip -DestinationPath ."
  - ps: "Move-Item pgp-win32-6.5.8-master\\libs .."
  - ps: "New-Item libs\\pgpcdk\\win32\\PGPcdk\\Debug -type directory"
  - ps: "Invoke-WebRequest https://ci.appveyor.com/api/buildjobs/k9hmupt0aumf8eu7/artifacts/libs/pgpcdk/win32/PGPcdk/Debug/PGPsdkStatic.lib -OutFile libs\\pgpcdk\\win32\\PGPcdk\\Debug\\PGPsdkStatic.lib"
  - cmd: "msbuild src\\win32\\PGPfone.sln /logger:\"C:\\Program Files\\AppVeyor\\BuildAgent\\Appveyor.MSBuildLogger.dll\""

artifacts:
  - name: PGPfone.exe
    path: "src\\win32\\Debug\\PGPfone.exe"
